server:
  port: 7901
user:
  userServicePath: http://localhost:7900/simple/
#将此服务注册到eureka上面
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
spring:
  application:
    name: microservice-consumer-movie